name: GAuction
version: 2.0
main: com.gsoldera.gAuction.GAuctionPlugin
description: Auction plugin for Minecraft
author: GSoldera
website: https://github.com/g-soldera/gAuction
depend: [Vault]
commands:
  auction:
    description: Comandos de leil達o
    aliases:
      - leilao
      - leil達o
  auctionadmin:
    description: Comandos administrativos de leil達o
    aliases:
      - leilaoadmin
      - leil達oadmin