name: GAuction
version: 2.0
main: com.gsoldera.gAuction.GAuctionPlugin
description: Auction plugin for Minecraft
author: GSoldera
website: https://github.com/g-soldera/gAuction
depend: [Vault]
commands:
  auction:
    description: Auction commands
    permission: gauction.use
    permission_create: gauction.create
    aliases:
      - leilao
      - leilão
      
  auctionadmin:
    description: Auction admin commands
    permission: gauction.admin
    aliases:
      - leilaoadmin
      - leilãoadmin

resources:
  - messages_en-US.yml
  - messages_pt-BR.yml
  - config.yml
